### ISSUE TITLE
Parameter learning behaviour on BN example

### ISSUE THREAD

**Issue by plison** [ML-KULeuven/problog#98]
I've noticed a strange result when doing parameter learning, where I get a different result depending on whether the parameter to tune is (a) directly associated with the rule or is (b) associated to a probabilistic fact included in the clauses of the rule.

From the Bayesian network example:
```
t(0.5)::burglary.
0.2::earthquake.
t(0.5)::p_alarm1.
t(0.5)::p_alarm2.
t(0.5)::p_alarm3.

alarm :- burglary, earthquake, p_alarm1.
alarm :- burglary, \+earthquake, p_alarm2.
alarm :- \+burglary, earthquake, p_alarm3.
```
with the following evidence:
```
evidence(burglary,false).
evidence(alarm,false).
-----
evidence(earthquake,false).
evidence(alarm,true).
evidence(burglary,true).
-----
evidence(burglary,false).
```

In this case, I get P(burglary) = 0.3333, P(alarm1) = 0.5, P(alarm2) = 1 and P(alarm3) = 0.

However, if I try to attach those tunable parameters to the rule directly, I do not the get the same results when running LFI on the same evidence:

```
t(0.5)::burglary.
0.2::earthquake.

t(0.5)::alarm :- burglary, earthquake.
t(0.5)::alarm :- burglary, \+earthquake.
t(0.5)::alarm :- \+burglary, earthquake.
```
P(burglary) is still equal to 0.3333 and P(alarm2) is still equal to 1, but this time the probability of the first alarm is set to 0, even though no case of  burglary + alarm was observed in the evidence (so the probability should not be modified from the initial 0.5).

Any idea why this is the case?

**Comment by rmanhaeve** [comment]
Hi Pierre. This seems to be a bug indeed. We'll look into it.

**Comment by wenchiyang** [comment]
Thank you for your input!
It is indeed a bug that the algorithm blindly assigns a 0 to parameters whose value cannot be inferred in the evidence instead of choosing not to update, just like `p_alarm1 ` in your illustration. I have fixed it [here](https://github.com/ML-KULeuven/problog-dev/pull/26) which will soon be integrated in the current repo as well.

**Comment by rmanhaeve** [comment]
Reconfirming this on current `master` — the discrepancy is still present, so the fix mentioned above (problog-dev PR #26) either was never ported to this repository or does not cover the rule-annotated case.

Running both of your models against your evidence:

```
(a) parameters on facts:  [0.33333333, 0.5, 1.0, 0.0]   132 iterations
(b) parameters on rules:  [0.33333333, 0.0, 1.0, 0.0]     2 iterations
```

So `p_alarm1` correctly retains its 0.5 prior when nothing in the evidence constrains it, while the equivalent parameter annotated directly on the rule is driven to 0 — exactly as you described. The iteration counts (132 vs 2) suggest case (b) is converging degenerately rather than merely converging to a different optimum.

Keeping this open as a confirmed bug in LFI.

**Comment by rmanhaeve** [comment]
Fixed on the `2.2.11-fixes` branch (d071ee1).

The cause is a single missing check in `_update`. Its own debug output states the problem:

```
Update probabilistic fact (1, t): 0.0 / 0.0 = 0.0
```

A zero numerator was taken as evidence that the parameter is zero, without looking at the denominator. When a parameter is annotated on a rule, its expected counts are only accumulated over examples in which the body holds — and here no example has both `burglary` and `earthquake` true, so both numerator and denominator are zero. The same model with the parameter on a separate probabilistic fact keeps its prior, because such a fact is counted in every example. Hence the disagreement you found between two encodings of the same network.

`_update` now checks the denominator first and leaves the parameter where it is when the examples say nothing about it, which is what EM prescribes when there are no expected counts. Both encodings now give:

```
[0.33333333, 0.5, 1.0, 0.0]
```

so `p_alarm1` and its rule-annotated equivalent both stay at 0.5, exactly as you expected. A genuine zero — where the body does hold somewhere in the evidence, as for `p_alarm3` — is unaffected.

Thanks for the very precise report; the two models side by side made this straightforward to pin down.
